version: '3'
services:
  moonlake_db:
    image: postgres:13.5-alpine
    container_name: 'bookshelf-history-db'
    ports:
      - "65432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=bookshelf_history"
